### ISSUE TITLE
Add docs from Define your Bot conversation

### ISSUE THREAD

**Issue by iboldurev** [magento-hackathon/magebot#10]
Hi, please add how to use doc from Define your Bot conversation

**Comment by schmengler** [comment]
This is a hackathon project and still WIP, not ready for production

**Comment by iboldurev** [comment]
@schmengler I understand you, I am more interested in the implementation of dialogue through your code (ConversationDefinitionList)

**Comment by iboldurev** [comment]
@schmengler I'm interested in an example implementation ConversationDefinition
